spring:
  application:
    name: eureka-client

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 35
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
