server:
  port: 8882

spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  data:
    mongodb:
      database: moviedb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
